version: '3.8'

name: tic-tac-toe

services:
  backend:
    image: artsiomshshshsk/cloud-programming-lab:tic-tac-toe-back
    environment:
      - AWS_COGNITO_CLIENT_ID=${AWS_COGNITO_CLIENT_ID}
      - AWS_COGNITO_USER_POOL_ID=${AWS_COGNITO_USER_POOL_ID}
      - AWS_REGION=${AWS_REGION}
    ports:
      - "8081:8081"

  frontend:
    image: artsiomshshshsk/cloud-programming-lab:tic-tac-toe-front
    ports:
      - "8080:8080"
    depends_on:
      - backend