version: '3.8'

name: tic-tac-toe

services:
  backend:
    image: artsiomshshshsk/cloud-programming-lab:tic-tac-toe-back
    env_file:
      - .env
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: artsiomshshshsk/cloud-programming-lab:tic-tac-toe-front
    ports:
      - "8080:8080"
    depends_on:
      - backend