version: '3.8'

services:
  backend:
    build: ./tic-tac-toe-backend
    ports:
      - "8081:8081"

  frontend:
    build: ./tic-tac-toe-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend