name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./tic-tac-toe-frontend
          file: ./Dockerfile
          push: true
          tags: artsiomshshshsk/cloud-programming-lab:tic-tac-toe-front


      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./tic-tac-toe-backend
          file: ./Dockerfile
          push: true
          tags: artsiomshshshsk/cloud-programming-lab:tic-tac-toe-back
